services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./memdb"]
    environment:
      - SOCKET_PATH=/tmp/db.sock
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 60M
    restart: unless-stopped

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./main"]
    networks:
      - backend
      - payment-processor
    volumes:
      - memsock:/tmp
    depends_on:
      - worker
    environment:
      - SOCKET_PATH=/tmp/db.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080/payments
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 70M
    restart: unless-stopped

  app2:
    ports:
      - "6060:6060"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./main"]
    networks:
      - backend
      - payment-processor
    volumes:
      - memsock:/tmp
    depends_on:
      - worker
    environment:
      - SOCKET_PATH=/tmp/db.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080/payments
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 70M
    restart: unless-stopped

  haproxy:
    image: haproxy:latest
    container_name: haproxy-dev
    ports:
      - "9999:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 210M
    restart: unless-stopped

volumes:
  memsock:


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
