services:
  redis:
    image: redis:8-alpine
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50M"
    networks:
      - backend

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 100M

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
