services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./main"]
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    environment:
      - SOCKET_PATH=/tmp/api1.sock
      - OTHER_SOCKET_PATH=/tmp/api2.sock
      - SUMMARY_URL=http://app2:8080/internal/payments-summary
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080/payments
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 70M
    restart: unless-stopped

  app2:
    ports:
      - "6060:6060"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./main"]
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    environment:
      - SOCKET_PATH=/tmp/api2.sock
      - OTHER_SOCKET_PATH=/tmp/api1.sock
      - SUMMARY_URL=http://app1:8080/internal/payments-summary
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080/payments
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 70M
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - memsock:/tmp
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 210M
    restart: unless-stopped

volumes:
  memsock:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
