package config

import "os"

var REDIS_URL = os.Getenv("REDIS_URL")
var PROCESSOR_DEFAULT_URL = os.Getenv("PROCESSOR_DEFAULT_URL")
var PROCESSOR_FALLBACK_URL = os.Getenv("PROCESSOR_FALLBACK_URL")
var SUMMARY_URL = os.Getenv("SUMMARY_URL")
var SOCKET_PATH = os.Getenv("SOCKET_PATH")
var OTHER_SOCKET_PATH = os.Getenv("OTHER_SOCKET_PATH")
